AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Naming/MethodParameterName:
  Enabled: false

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/*_spec.rb'

Style/BlockDelimiters:
  Exclude:
    - 'spec/*_spec.rb'

Style/MixinUsage:
  Exclude:
    - 'features/support/*.rb'

Metrics/ParameterLists:
  Exclude:
    - 'features/step_definitions/*.rb'

Metrics/AbcSize:
  Exclude:
    - 'examples/**/*'

Metrics/MethodLength:
  Exclude:
    - 'examples/**/*'

Style/Semicolon:
  Exclude:
    - 'examples/**/*'

Layout/SpaceAroundOperators:
  Exclude:
    - 'examples/**/*'

Lint/AmbiguousOperator:
  Exclude:
    - 'examples/**/*'
