AllCops:
  TargetRubyVersion: 2.3

Metrics/BlockLength:
  Exclude:
    - 'spec/*_spec.rb'

Style/BlockDelimiters:
  Exclude:
    - 'spec/*_spec.rb'

Style/MixinUsage:
  Exclude:
    - 'features/support/*.rb'
