#!/usr/bin/env ruby
# frozen_string_literal: true

require 'bundler/setup'
require 'pry'
require 'glistening_ruby/dsl'
require stdlib 'colors'

shape.sphere :large_sphere do
  material do
    pattern.checkers do
      color rgb 0.1, 1.0, 0.5
      color rgb 0.9, 0.0, 0.5
      rotate z: 1/4r, y: 1/8r
      scale 2
    end
    diffuse 0.7
    phong 0.3
  end
  translate -0.5, 1, 0.5
end

shape.sphere :medium_sphere do
  material do
    pattern.gradient do
      color rgb 0.8, 0.8, 0.2
      color rgb 0.8, 0.2, 0.8
      color rgb 0.2, 0.8, 0.2
      rotate z: 1/8r
    end
    diffuse 0.7
    phong 0.3
  end
  scale 1/2r
  translate 1.5, 0.5, -0.5
end

shape.sphere :small_sphere do
  material do
    pattern.stripe do
      color rgb 1.0, 0.8, 0.1
      color rgb 0.0, 0.2, 0.9
      rotate z: 1/8r, x: 1/4r
      scale 1/3r
    end
    diffuse 0.7
    phong 0.3
  end
  scale 1/3r
  translate -1.5, 0.33, -0.75
end

scene.pry do
  light.spherical { translate 0, 10, -10; falloff 0 }

  shape.plane do
    material do
      pattern.ring do
        color rgb 1.0, 0.9, 0.9
        color rgb 0.5, 0.5, 0.5
        color rgb 0.0, 0.1, 0.1
        color rgb 0.5, 0.5, 0.5
      end
      phong 0
    end
  end

  shape :large_sphere
  shape :medium_sphere
  shape :small_sphere

  camera do
    canvas 320, 256, 1/6r
    position 2, 1.5, -3.5
    look_at 0, 1, 0
  end
end
