#!/usr/bin/env ruby
# frozen_string_literal: true

require 'bundler/setup'
require 'pry'
require 'glistening_ruby/dsl'

require_relative 'include/cocktail'
require_relative 'include/table'

shape.cube :floor_ceiling do
  material do
    pattern.stripe do
      color grey 0.9
      pattern.checkers do
        color grey 0.2
        color grey 0.8
        scale 1/32r
        rotate x: 1/8r
      end
      scale 2
      rotate z: 1/4r
    end
    ambient 0.3
    diffuse 0.7
    phong 0.7
    reflective 0.1
  end
  translate 0, 1, 0
  scale 10, 1.5, 10
end

shape.cube :walls do
  material do
    pattern.stripe do
      color rgb 0.7, 0.5, 0.3
      color rgb 0.3, 0.5, 0.7
      scale 1/16r
      rotate y: 1/8r
    end
    phong 0
  end
  scale 5, 10, 5
end

shape.group :room do
  shape :floor_ceiling
  shape :walls
end

scene.pry do
  light.spherical { translate -2, 2.5, -2 }

  shape :room
  shape.group do
    shape :table
    shape :cocktail do
      translate 0, 0.851, 0
    end
    translate 0, 0, 1
  end

  camera do
    canvas 320, 256
    position 0.1, 1.2, 0.5
    look_at 0, 0.9, 1.2
  end
end
