#!/usr/bin/env ruby
# frozen_string_literal: true

require 'bundler/setup'
require 'pry'
require 'glistening_ruby/dsl'

require_relative 'include/cocktail'

shape.cube :floor_ceiling do
  material do
    pattern.stripe do
      color grey 0.9
      pattern.checkers do
        color grey 0.2
        color grey 0.8
        scale 1/32r
        rotate x: 1/8r
      end
      scale 2
      rotate z: 1/4r
    end
    ambient 0.3
    diffuse 0.7
    phong 0.7
    reflective 0.1
  end
  translate 0, 1, 0
  scale 10, 1.5, 10
end

shape.cube :walls do
  material do
    pattern.stripe do
      color rgb 0.7, 0.5, 0.3
      color rgb 0.3, 0.5, 0.7
      scale 1/16r
      rotate y: 1/8r
    end
    phong 0
  end
  scale 5, 10, 5
end

shape.group :room do
  shape :floor_ceiling
  shape :walls
end

shape.group :table do
  material do
    pattern.perturb do
      pattern.stripe do
        color rgb 0.5, 0.35, 0.15
        color rgb 0.45, 0.3, 0.1
        scale 1/32r
      end
      magnitude 0.2
      octaves 2
    end
    phong 0.3
    reflective 0.05
  end

  shape.cube do
    scale 1.25, 0.05, 0.5
    translate 0, 0.8, 0
  end

  [-1, 1].each do |x|
    [-1, 1].each do |z|
      shape.cube do
        scale 0.05, 0.4, 0.05
        translate(x * 1.2, 0.4, z * 0.45)
      end
    end
  end
end

scene.pry do
  light { point -2, 2.5, -2 }

  shape :room
  shape.group do
    shape :table
    shape :cocktail do
      translate 0, 0.851, 0
    end
    translate 0, 0, 1
  end

  camera do
    canvas 320, 256
    position 0.1, 1.2, 0.5
    look_at 0, 0.9, 1.2
  end
end
