#!/usr/bin/env ruby
# frozen_string_literal: true

require 'bundler/setup'
require 'pry'
require 'glistening_ruby/dsl'

shape.group :hexagon do
  material do
    color rgb 1.0, 0.8, 0.5
    phong 0.9, 300
    reflective 0.9
  end
  0.upto 5 do |n|
    shape :side, n
  end
end

shape.group :side do |side|
  shape.sphere do
    scale 1/4r
  end
  shape.cylinder do
    scale 0.25, 1, 0.25
    rotate z: -1/4r, y: -1/12r
  end
  translate 0, 0, -1
  rotate y: Rational(side, 6)
end

scene.pry do
  light { point -2, 2.5, -2 }

  shape :hexagon

  camera do
    canvas 320, 256, 1/6r
    position 1.5, 1.2, -1.3
    look_at 0, 0, 0
  end
end
