#!/usr/bin/env ruby
# frozen_string_literal: true

require 'bundler/setup'
require 'pry'
require 'glistening_ruby/dsl'

require_relative 'include/cocktail'
require_relative 'include/utah_teapot'

pattern.checkers :grey_tiles do
  color rgb 0.5, 0.5, 0.5
  color rgb 0.75, 0.75, 0.75
  translate 0.999, 0.999, 0
  scale 1/8r
end

material :shiny_tiles do
  pattern :grey_tiles
  ambient 0.3
  diffuse 0.5
  phong 0.6, 50
  reflective 0.2
end

shape.cube :room do
  material :shiny_tiles
  translate 0, 1, 0
  scale 3
end

scene.pry do
  light { point -1.5, 2.5, -1.5; color rgb 1.0, 1.0, 1.0 }

  shape :room

  shape :cocktail do
    scale 3.5
    translate 0.8, 0.01, -0.5
  end

  shape :utah_teapot do
    rotate y: -1/12r
  end

  camera do
    canvas 320, 256
    position 1.0, 1.2, -2.9
    look_at 0.05, 0.3, 0.8
  end
end
