#!/usr/bin/env ruby
# frozen_string_literal: true

require 'bundler/setup'
require 'pry'
require 'glistening_ruby/dsl'

material :glass do
  color rgb 0.1, 0.2, 0.1
  ambient 0.1
  diffuse 0.2
  phong 0.9, 300
  reflective 0.9
  transparent 0.9, 1.5
end

shape.sphere :large_sphere do
  material :glass
  translate -0.5, 1, 0.5
end

material :yellow_green_gradient do
  pattern.gradient do
    color rgb 0.8, 0.8, 0.2
    color rgb 0.8, 0.2, 0.8
    color rgb 0.2, 0.8, 0.2
    rotate z: 1/8r
  end
  diffuse 0.7
  phong 0.3
  reflective 0.2
end

shape.sphere :medium_sphere do
  material :yellow_green_gradient
  scale 1/2r
  translate 1.5, 0.5, -0.5
end

material :blue_yellow_stripes do
  pattern.stripe do
    color rgb 1.0, 0.8, 0.1
    color rgb 0.0, 0.2, 0.9
    scale 1/3r
    rotate z: 1/8r, x: 1/4r
  end
  diffuse 0.7
  phong 0.3
end

shape.sphere :small_sphere do
  material :blue_yellow_stripes
  scale 1/3r
  translate -1.5, 0.33, -0.75
end

material :water do
  color rgb 0.0, 0.1, 0.1
  ambient 0.2
  diffuse 0.2
  phong 0.8
  reflective 0.9
  transparent 0.9, 1.1
end

shape.plane :water do
  material :water
  shadows false
  translate 0, 0.5, 0
end

material :sky do
  color rgb 0.2, 0.5, 1.0
  ambient 0.8
  diffuse 0.2
  phong 0
end

shape.plane :sky do
  material :sky
  shadows false
  translate 0, 100, 0
end

material :red_blue_grey_plaid do
  width = 1/2r**0.5
  pattern.stripe :grey_stripes do
    color rgb 0.3, 0.3, 0.3
    color rgb 0.7, 0.7, 0.7
    rotate y: 1/8r
    scale width
  end
  pattern.stripe :red_blue_stripes do
    color rgb 0.7, 0.3, 0.2
    color rgb 0.2, 0.3, 0.7
    rotate y: -1/8r
    scale width
  end
  phong 0
end

shape.plane :floor do
  material :red_blue_grey_plaid
end

scene.pry do
  light { point 0, 10, -10; color rgb 0.4, 0.5, 0.7 }
  light { point 5, 5, -10; color rgb 0.7, 0.5, 0.4 }

  shape :floor
  shape :water
  shape :sky
  shape :large_sphere
  shape :medium_sphere
  shape :small_sphere

  camera do
    canvas 320, 256
    position 3, 2, -5
    look_at 0, 1, 0
  end
end
